import crypto from "node:crypto";
import type { Db, Product, ProductCategory, ProductStockStatus } from "./types";
import type { ProductImage, ProductView, MediaAsset } from "./admin-types";
import { adminStore, recordAdminActivity } from "./admin-store";

type Actor = { userId: string; name: string };
export class CatalogueError extends Error { constructor(message: string, public status = 400) { super(message); } }
const id = (prefix: string) => `${prefix}_${crypto.randomBytes(8).toString("hex")}`;
const now = () => new Date().toISOString();
const str = (value: unknown, max = 20000) => typeof value === "string" ? value.trim().slice(0, max) : "";
function required(value: unknown, label: string) { const result = str(value, 200); if (!result) throw new CatalogueError(`${label} is required.`); return result; }
export function safeMediaUrl(value: unknown): string { const url = str(value, 2000); if (!url) return ""; if (/^\/(?!\/)[^\\\s]*$/.test(url)) return url; try { const parsed = new URL(url); if (["http:", "https:"].includes(parsed.protocol) && !parsed.username && !parsed.password) return url; } catch {} throw new CatalogueError("Use an http(s) URL or a local /path."); }
function integer(value: unknown, label: string) { const n = typeof value === "number" ? value : Number(value); if (!Number.isSafeInteger(n) || n < 0) throw new CatalogueError(`${label} must be a non-negative whole number.`); return n; }
const views: ProductView[] = ["hero", "front", "left", "right", "rear", "top", "ports", "installation", "vehicle", "accessories", "other"];
const statuses: ProductStockStatus[] = ["in-stock", "low-stock", "out-of-stock", "available-on-order", "discontinued"];
export function productImages(product: Product): ProductImage[] { if (product.images?.length) return [...product.images].sort((a,b) => a.order-b.order); return [...new Set([product.image, ...(product.gallery ?? [])].filter(Boolean))].map((src, i) => ({ id: `legacy_${i}`, src, sourceType: src.startsWith("/uploads/") ? "upload" : "url", viewType: i ? "other" : "hero", alt: product.name, order: i, primary: i === 0 })); }
export function stockStatus(product: Product): ProductStockStatus { if (product.stockStatus === "available-on-order" || product.stockStatus === "discontinued" || product.trackInventory === false) return product.stockStatus ?? "available-on-order"; const q = product.stockQuantity ?? 0; return q === 0 ? "out-of-stock" : q <= (product.lowStockThreshold ?? 5) ? "low-stock" : "in-stock"; }
function history(db: Db, product: Product, previous: number, reason: string, notes: string, actor: Actor) { const quantity = product.stockQuantity ?? 0; adminStore(db).inventoryHistory.push({ id: id("stock"), productId: product.id, productName: product.name, actorId: actor.userId, actorName: actor.name, previous, quantity, change: quantity-previous, reason, notes, createdAt: now() }); }
export function saveProduct(db: Db, input: Record<string, unknown>, actor: Actor, productId?: string): Product {
  const old = productId ? db.products.find(p => p.id === productId) : undefined;
  if (productId && !old) throw new CatalogueError("Product not found.", 404);
  if (old && input.updatedAt && input.updatedAt !== old.updatedAt) throw new CatalogueError("This product changed. Reload before saving.", 409);
  const data: Record<string, unknown> = { ...old, ...input };
  const name = required(data.name, "Product name"), slug = required(data.slug, "Slug");
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new CatalogueError("Slug must contain lowercase letters, numbers and hyphens.");
  if (db.products.some(p => p.id !== productId && p.slug === slug)) throw new CatalogueError("This product slug already exists.", 409);
  const selectedCategory = required(data.category, "Category");
  const categoryRecord = db.productCategories.find(c => c.slug === selectedCategory || c.name === selectedCategory || c.id === selectedCategory);
  if (!categoryRecord) throw new CatalogueError("Choose an existing category.");
  const category = categoryRecord.name;
  const sku = str(data.sku, 120); if (sku && db.products.some(p => p.id !== productId && p.sku?.toLowerCase() === sku.toLowerCase())) throw new CatalogueError("This SKU already exists.", 409);
  const list = (v: unknown): string[] => Array.isArray(v) ? v.map(x => str(x)).filter(Boolean).slice(0,200) : [];
  const pairs = (v: unknown) => Array.isArray(v) ? v.slice(0,200).map(x => { if (!x || typeof x !== "object") throw new CatalogueError("Invalid specification."); const row = x as Record<string,unknown>; return {label: str(row.label,200),value:str(row.value)}; }) : [];
  let images = old ? productImages(old) : [];
  if (data.images !== undefined) { if (!Array.isArray(data.images) || data.images.length > 100) throw new CatalogueError("Use at most 100 images."); images = data.images.map((value,index) => { if (!value || typeof value !== "object") throw new CatalogueError("Invalid image."); const row = value as Record<string,unknown>; const src = safeMediaUrl(row.src); if (!src) throw new CatalogueError("Image URL is required."); const viewType = views.includes(row.viewType as ProductView) ? row.viewType as ProductView : "other"; return {id: str(row.id) || id("img"),src,sourceType: src.startsWith("/uploads/") ? "upload" as const : "url" as const,viewType,alt:str(row.alt,500),order:integer(row.order ?? index,"Image order"),primary:row.primary === true}; }).sort((a,b) => a.order-b.order); }
  const primary = Math.max(0, images.findIndex(x => x.primary)); images = images.map((x,i) => ({...x,primary:i===primary}));
  const docs = Array.isArray(data.documents) ? data.documents.map(value => { if (!value || typeof value !== "object") throw new CatalogueError("Invalid document."); const row = value as Record<string,unknown>; return {name:required(row.name,"Document title"),type:str(row.type,100),url:safeMediaUrl(row.url),size:str(row.size,100)}; }) : [];
  if (docs.some(d => !d.url)) throw new CatalogueError("Document URL is required.");
  const product: Product = { ...old, id: old?.id ?? id("product"), kind:"product", createdAt:old?.createdAt ?? now(), updatedAt:now(), order:integer(data.order ?? 0,"Display order"), published:data.published === true, name,slug,category,brand:str(data.brand,120),sku,tagline:str(data.tagline),description:list(data.description),image:images[primary]?.src ?? (data.images !== undefined ? "" : safeMediaUrl(data.image)),images,gallery:images.map(x=>x.src),specs:pairs(data.specs),documents:docs,price:str(data.price,100),priceNote:str(data.priceNote),featured:data.featured===true, modelNumber:str(data.modelNumber,200),shortDescription:str(data.shortDescription),subcategory:str(data.subcategory,200),seoTitle:str(data.seoTitle,200),seoDescription:str(data.seoDescription,500),ogImage:safeMediaUrl(data.ogImage),priceOnRequest:data.priceOnRequest===true,features:list(data.features),highlights:list(data.highlights),benefits:list(data.benefits),compatibility:list(data.compatibility),inBox:list(data.inBox),relatedProductSlugs:list(data.relatedProductSlugs),stockQuantity:integer(data.stockQuantity ?? 0,"Stock quantity"),lowStockThreshold:integer(data.lowStockThreshold ?? 5,"Low stock threshold"),trackInventory:data.trackInventory !== false,stockStatus:statuses.includes(data.stockStatus as ProductStockStatus) ? data.stockStatus as ProductStockStatus : "in-stock" };
  if (/^(on request|price on request|contact for pric(e|ing))$/i.test(product.price)) product.priceOnRequest = true;
  if (product.price && !product.priceOnRequest && (!Number.isFinite(Number(product.price.replace(/[,₹\s]/g,""))) || Number(product.price.replace(/[,₹\s]/g,"")) < 0)) throw new CatalogueError("Price must be a non-negative amount or use Price on Request.");
  product.stockStatus = stockStatus(product);
  if (old) db.products[db.products.indexOf(old)] = product; else db.products.push(product);
  if ((old?.stockQuantity ?? 0) !== product.stockQuantity) history(db,product,old?.stockQuantity ?? 0,old ? "Product editor adjustment" : "Opening stock",str(input.inventoryNotes),actor);
  recordAdminActivity(db,actor,old ? "update" : "create","products",product.id,product.name); return product;
}
export function adjustInventory(db: Db, input: Record<string,unknown>, actor: Actor) { const p = db.products.find(x=>x.id === input.productId); if (!p) throw new CatalogueError("Product not found.",404); const q = integer(input.quantity,"Quantity"), reason=required(input.reason,"Reason"), previous=p.stockQuantity ?? 0; if (!["add","reduce","set"].includes(String(input.type))) throw new CatalogueError("Invalid adjustment type."); const quantity = integer(input.type === "add" ? previous+q : input.type === "reduce" ? previous-q : q,"Resulting stock"); p.stockQuantity=quantity; p.stockStatus=stockStatus(p); p.updatedAt=now(); history(db,p,previous,reason,str(input.notes),actor); recordAdminActivity(db,actor,"adjust","inventory",p.id,`${p.name}: ${previous} → ${quantity}; ${reason}`); return p; }
export function saveCategory(db: Db, input: Record<string,unknown>, actor: Actor, categoryId?: string) { const old=db.productCategories.find(x=>x.id===categoryId); if(categoryId&&!old) throw new CatalogueError("Category not found.",404); const data={...old,...input}; const name=required(data.name,"Category name"),slug=required(data.slug,"Slug"); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new CatalogueError("Use a lowercase hyphenated slug."); if(db.productCategories.some(c=>c.id!==categoryId&&(c.slug===slug||c.name.toLowerCase()===name.toLowerCase()))) throw new CatalogueError("Category name or slug already exists.",409); const category:ProductCategory={id:old?.id??id("category"),kind:"productCategory",name,slug,description:str(data.description),image:safeMediaUrl(data.image),order:integer(data.order??0,"Order"),published:data.published!==false,createdAt:old?.createdAt??now(),updatedAt:now()}; if(old){db.productCategories[db.productCategories.indexOf(old)]=category; for(const p of db.products){if(p.category===old.slug)p.category=slug;else if(p.category===old.name)p.category=name;}}else db.productCategories.push(category); recordAdminActivity(db,actor,old?"update":"create","categories",category.id,name); return category; }
export function mediaReferences(db: Db,url:string):string[]{ const references:string[]=[]; const has=(v:unknown):boolean=>typeof v==="string"?v===url:Array.isArray(v)?v.some(has):!!v&&typeof v==="object"?Object.values(v).some(has):false; for(const [key,value] of Object.entries(db)){if(["admin","sessions","users","customers"].includes(key))continue;if(Array.isArray(value)){for(const row of value){if(has(row))references.push(`${key}: ${String(row.name??row.title??row.id)}`);}}else if(has(value))references.push(key);}return references; }
export function saveMedia(db:Db,input:Record<string,unknown>,actor:Actor,mediaId?:string):MediaAsset{const old=adminStore(db).media.find(x=>x.id===mediaId);if(mediaId&&!old)throw new CatalogueError("Media not found.",404);const data={...old,...input}; const url=safeMediaUrl(data.url);if(!url)throw new CatalogueError("URL is required."); const item:MediaAsset={id:old?.id??id("media"),name:required(data.name,"Name"),url,mimeType:str(data.mimeType,100)||"application/octet-stream",category:str(data.category,100)||"Documents",sourceType:old?.sourceType??"url",size:old?.size,createdAt:old?.createdAt??now(),updatedAt:now()};if(old)adminStore(db).media[adminStore(db).media.indexOf(old)]=item;else adminStore(db).media.push(item);recordAdminActivity(db,actor,old?"update":"create","media",item.id,item.name);return item;}
export function deleteCatalogueRecord(db:Db,kind:string,recordId:string,actor:Actor){if(kind==="products"){const p=db.products.find(x=>x.id===recordId);if(!p)throw new CatalogueError("Product not found.",404);db.products=db.products.filter(x=>x.id!==recordId);}else if(kind==="categories"){const c=db.productCategories.find(x=>x.id===recordId);if(!c)throw new CatalogueError("Category not found.",404);if(db.products.some(p=>[c.id,c.slug,c.name].includes(p.category)))throw new CatalogueError("Reassign all products before deleting this category.",409);db.productCategories=db.productCategories.filter(x=>x.id!==recordId);}else if(kind==="media"){const m=adminStore(db).media.find(x=>x.id===recordId);if(!m)throw new CatalogueError("Media not found.",404);const refs=mediaReferences(db,m.url);if(refs.length)throw new CatalogueError(`Media is referenced by ${refs.slice(0,4).join(", ")}.`,409);adminStore(db).media=adminStore(db).media.filter(x=>x.id!==recordId);}else throw new CatalogueError("Unknown module.",404);recordAdminActivity(db,actor,"delete",kind,recordId,`Deleted ${kind} record`);return{ok:true};}
