"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { CheckoutSummary } from "@/lib/checkout";
import styles from "./checkout.module.css";
const money=(amount:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(amount/100);
export default function CheckoutPage(){
  const[data,setData]=useState<CheckoutSummary|null>(null),[loading,setLoading]=useState(true),[signedOut,setSignedOut]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let active=true;fetch("/api/customer/checkout",{cache:"no-store"}).then(async res=>{if(!active)return;if(res.status===401||res.status===403){setSignedOut(true);return;}if(!res.ok)throw Error("Unable to load checkout. Please try again.");const result=await res.json();if(active)setData(result);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  return <div className={styles.page}><div className={styles.shell}>
    <Link href="/cart" className={styles.back}>← Back to cart</Link><h1>Review your purchase</h1><p className={styles.intro}>Your products, delivery details and payment options in one place.</p>
    {loading?<p role="status">Loading checkout…</p>:signedOut?<section className={styles.card}><h2>Sign in to continue</h2><p>Your checkout uses the cart saved to your customer account.</p><Link className={styles.button} href="/customer-login?next=/checkout">Sign in</Link></section>:error?<p role="alert">{error}</p>:!data?.items.length?<section className={styles.card}><h2>Your cart is empty</h2><Link className={styles.button} href="/products">Explore products</Link></section>:<div className={styles.grid}>
      <div className={styles.stack}><section className={styles.card}><h2>Your products</h2>{data.items.map(item=><article key={item.productId} className={styles.item}>{item.image&&<img src={item.image} alt={item.name}/>}<div><strong>{item.name}</strong><p>Quantity: {item.quantity}</p>{!item.available&&<span className={styles.warning}>Availability needs confirmation</span>}</div><strong>{item.lineAmount===null?"Quote required":money(item.lineAmount)}</strong></article>)}</section>
      <section className={styles.card}><h2>Delivery details</h2><p>Delivery is confirmed with our team when you place your order.</p><div className={styles.fields}>{[{name:"name",label:"Full name",type:"text",auto:"name"},{name:"phone",label:"Phone",type:"tel",auto:"tel"},{name:"address",label:"Street address",type:"text",auto:"street-address"},{name:"city",label:"City",type:"text",auto:"address-level2"},{name:"state",label:"State",type:"text",auto:"address-level1"},{name:"postal",label:"PIN code",type:"text",auto:"postal-code"}].map(field=><label key={field.name}>{field.label}<input name={field.name} type={field.type} autoComplete={field.auto} maxLength={field.name==="postal"?6:200}/></label>)}</div><p className={styles.note}>These details are not submitted or saved yet.</p></section>
      <section className={styles.card}><h2>Payment options</h2><p>Online payments will be available soon.</p><div className={styles.methods}>{data.methods.map(method=><div key={method.id}><strong>{method.label}</strong><span>Coming soon</span><p>{method.description}</p></div>)}</div></section></div>
      <aside className={styles.card}><h2>Order summary</h2><div className={styles.total}><span>Product subtotal</span><strong>{data.subtotal===null?"To be quoted":money(data.subtotal)}</strong></div><p>GST, delivery and installation charges will be confirmed before payment.</p>{data.needsQuotation&&<p className={styles.warning}>Some products require a quotation.</p>}{data.hasUnavailableItems&&<p className={styles.warning}>Please confirm availability before ordering.</p>}<button className={styles.pay} disabled>Online payment coming soon</button><Link className={styles.button} href="/contact">Contact us to purchase</Link><p className={styles.note}>No payment is collected and no order is placed on this page.</p></aside>
    </div>}
  </div></div>;
}
