export const mining={
  nav:["Solutions","Products","Industries","Resources","Company"],
  hero:{eyebrow:"MINING & EXTRACTIVE OPERATIONS",title:"Visibility that keeps heavy operations moving.",description:"RoadLenz gives mining teams real-time visibility, proven safety evidence, and data-driven control across every haul road and heavy asset.",status:["Haul Truck DT213","Moving","Crusher Plant Route","Fuel 62%","Normal"]},
  challenges:[{title:"Blind equipment movement",text:"Limited visibility across haul roads and active work zones."},{title:"Safety events without evidence",text:"No reliable video or data to understand what happened and why."},{title:"Fuel and uptime uncertainty",text:"Unknown fuel usage and machine health impact productivity and margins."}],
  stats:[["Asset","Haul Truck DT213"],["Status","Moving"],["Speed","24 km/h"],["Location","Haul Road H7"],["Destination","Crusher Plant"],["ETA","16 min"],["Payload","41.2 / 65.0 t"],["Fuel Level","62%"],["Engine Hours","3,842 h"],["Last Update","10:32:18 AM"]],
  stages:[{title:"Site Entry",time:"10:12 AM",detail:"Entered via Gate 3 · Driver ID verified",state:"Completed",progress:16},{title:"Work Zone",time:"10:24 AM",detail:"Hauling to Crusher Plant · Speed compliant",state:"In Progress",progress:55},{title:"Safety Review",time:"10:31 AM",detail:"Approaching safety review area · Video event detected",state:"Pending",progress:88}],
  devices:[{name:"4CH MDVR",image:"/images/mdvr.png",benefit:"Records up to 4 channels in 1080p for reliable incident evidence."},{name:"GPS Tracker",image:"/images/gps-tracker.png",benefit:"Real-time location, geofences, and route playback."},{name:"AI Dashcam",image:"/images/ai-dashcam.png",benefit:"Detects risky events and driver behavior in real time."},{name:"Side View Camera",image:"/images/side-camera.png",benefit:"Eliminates blind spots during lane changes and loading."},{name:"Fuel Sensor",image:"/images/fuel-sensor.png",benefit:"Accurate fuel level and consumption monitoring."}],
  reasons:["End-to-end visibility across every haul cycle","Clear video evidence for faster decisions","Proactive safety with AI event detection","Improved uptime through smarter insights","Lower operating costs and fuel savings"],
  benefits:[{title:"Fewer site incidents",text:"AI-powered alerts and visibility help prevent incidents before they happen."},{title:"Better equipment uptime",text:"Real-time monitoring and insights help reduce downtime and keep assets productive."},{title:"Controlled fuel use",text:"Accurate fuel data and driver insights reduce waste and improve efficiency."},{title:"Clearer compliance",text:"Video and data logs simplify audits and demonstrate compliance with confidence."}],
  faqs:[{q:"How does RoadLenz improve safety on mining sites?",a:"RoadLenz combines live vehicle visibility, AI event detection and synchronized video evidence so teams can identify risk sooner and investigate events with reliable context."},{q:"Can RoadLenz work in remote areas with poor connectivity?",a:"Compatible devices can retain operational and video data locally and synchronize it when connectivity becomes available."},{q:"Is the system compatible with our existing equipment?",a:"RoadLenz hardware is designed for professional installation across a broad range of heavy vehicles and auxiliary mining equipment."},{q:"How is video data stored and secured?",a:"Video is recorded to protected onboard storage with controlled remote access and configurable retention."}]
} as const;
