"use client";
import { useEffect,useRef,useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Icon } from "@/components/ui";
import { resourceSections,resourceTypeLabels,resourceHref,searchDocumentation,type PublicResource } from "@/lib/resource-content";
import ResourceMedia from "./ResourceMedia";
import styles from "./ResourcesHub.module.css";
const reveal={"data-reveal":"",initial:{opacity:0,y:12},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.1},transition:{duration:.4}};
export function ResourceEmpty({title,text,dark=false}:{title:string;text:string;dark?:boolean}) { return <div className={`${styles.empty} ${dark ? styles.emptyDark : ""}`}><Icon name="doc" /><div><h3>{title}</h3><p>{text}</p></div></div>; }
function SectionLink({href,children}:{href:string;children:React.ReactNode}) {return <a href={href} onClick={()=>{if(href==="#resource-library") document.getElementById("resource-library")?.setAttribute("open","");}} className={styles.sectionLink}>{children}<Icon name="arrowRight" /></a>;}
function downloadHref(file:string) {return file.startsWith("/api/") ? `${file}?download=1` : file;}
export default function ResourcesHub({resources,categories,initialSection="insights"}:{resources:PublicResource[];categories:{name:string;slug:string}[];initialSection?:string}) {
  const guides=resources.filter(r=>["guide","insight","checklist"].includes(r.type));
  const featured=guides.find(r=>r.featured) ?? guides.find(r=>r.type === "guide") ?? guides[0];
  const videos=resources.filter(r=>["video","webinar"].includes(r.type));
  const [selectedVideo,setSelectedVideo]=useState(videos[0]?.id);
  const video=videos.find(v=>v.id === selectedVideo) ?? videos[0];
  const [videoFailed,setVideoFailed]=useState(false);
  const [videoDuration,setVideoDuration]=useState("");
  const downloads=resources.filter(r=>r.file);
  const cases=resources.filter(r=>r.type === "case-study");
  const faqs=resources.filter(r=>r.type === "faq" && r.answer.trim());
  const [active,setActive]=useState(initialSection);
  const [query,setQuery]=useState("");
  const [category,setCategory]=useState("");
  const documents=searchDocumentation(resources,query,category);
  const rack=useRef<HTMLDivElement>(null);
  const navigator=useRef<HTMLElement>(null);
  useEffect(()=>{
    const nav=navigator.current;
    const link=nav?.querySelector<HTMLElement>('[aria-current="location"]');
    if(nav && link && nav.scrollWidth>nav.clientWidth) nav.scrollTo({left:link.offsetLeft-(nav.clientWidth-link.clientWidth)/2,behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth"});
  },[active]);
  useEffect(()=>{
    let frame=0;
    const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{
      const header=parseFloat(getComputedStyle(document.documentElement).getPropertyValue("--site-header-height")) || 72;
      const offset=header+(navigator.current?.offsetHeight ?? 66)+35;
      const positions=resourceSections.map(section=>({id:section.id,top:document.getElementById(section.id)?.getBoundingClientRect().top ?? Infinity})).filter(section=>section.top<=offset).sort((a,b)=>b.top-a.top);
      setActive(previous=> {const nearest=positions[0];if(!nearest) return "insights";return positions.some(p=>p.id===previous && Math.abs(p.top-nearest.top)<2) ? previous : nearest.id;});
    });};
    window.addEventListener("scroll",update,{passive:true});update();
    if(initialSection !== "insights" && !window.location.hash) document.getElementById(initialSection)?.scrollIntoView({behavior:"instant"});
    return()=>{cancelAnimationFrame(frame);window.removeEventListener("scroll",update);};
  },[initialSection]);
  const moveRack=(direction:number)=>{const element=rack.current;if(element) element.scrollBy({left:direction*element.clientWidth*.75,behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth"});};
  const rows=resources.filter(r=>r.id!==featured?.id && r.type!=="faq").slice(0,4);
  return <div className={styles.page}>
    <section className={styles.hero} aria-labelledby="resources-heading"><svg className={styles.heroRoute} viewBox="0 0 700 400" fill="none" aria-hidden="true"><path d="M400 20C300 90 650 110 540 220S280 270 350 390" /><circle cx="400" cy="20" r="7"/><circle cx="540" cy="220" r="7"/><circle cx="350" cy="390" r="7"/></svg><div className={styles.heroInner}><div className={styles.heroCopy}><motion.p {...reveal} className={styles.eyebrow}>RoadLenz Resources</motion.p><motion.h1 {...reveal} transition={{delay:.06}} id="resources-heading">Knowledge for<br />every mile ahead.</motion.h1><motion.p {...reveal} transition={{delay:.12}}>Practical guidance, product resources and fleet intelligence to help your operation move with more clarity.</motion.p><motion.div {...reveal} transition={{delay:.18}}><a href="#insights" className={styles.button}>Explore resources<Icon name="arrowRight" /></a></motion.div><div className={styles.heroBenefits}>{[{icon:"doc",title:"Real insights",text:"Practical and relevant"},{icon:"settings",title:"Built for fleets",text:"From the road to your team"},{icon:"route",title:"A smarter tomorrow",text:"Knowledge in motion"}].map(item=><div key={item.title}><Icon name={item.icon}/><span>{item.title}<small>{item.text}</small></span></div>)}</div></div><motion.div {...reveal} className={styles.heroComposition} aria-hidden="true"><div className={styles.heroBook}>{featured ? <ResourceMedia resource={featured} cover priority /> : <div className={styles.blankBook}><Icon name="doc"/><strong>RoadLenz<br/>Resource library</strong><span>Guidance for the road ahead</span></div>}</div><div className={styles.heroSheet}><span>RoadLenz</span><strong>Clarity for<br/>every journey.</strong><i/><i/><i/><i/><Icon name="shield"/></div><div className={styles.heroPhone}><span>RoadLenz</span><div><Icon name="play" /></div><strong>{video?.title ?? "Video learning"}</strong><small>{video?.meta ?? "Tutorials coming soon"}</small></div></motion.div></div></section>
    <nav ref={navigator} className={styles.navigator} aria-label="Resource sections">{resourceSections.map(section=><a key={section.id} href={`#${section.id}`} onClick={()=>setActive(section.id)} aria-current={active===section.id ? "location" : undefined}><Icon name={section.icon}/>{section.label}</a>)}</nav>
    <section id="insights" className={styles.shelf} aria-labelledby="shelf-heading"><div className={styles.sectionHeader}><div><p className={styles.eyebrow}>Featured resource</p><h2 id="shelf-heading">Start with what you need.</h2></div><p>Guides, tools, videos and real-world insights —<br/> all in one place, built for fleet operators.</p><SectionLink href="#resource-library">Explore all resources</SectionLink></div>{featured ? <div className={styles.featureGrid}><motion.article {...reveal} className={styles.featureCard}><div key="cover"><ResourceMedia resource={featured} cover/></div><div key="copy" className={styles.featureCopy}><p className={styles.eyebrow}>Featured {resourceTypeLabels[featured.type]}</p><h3>{featured.title}</h3><p>{featured.description}</p><Link href={resourceHref(featured)} className={styles.button}>Read {featured.type === "insight" ? "insight" : "guide"}<Icon name="arrowRight"/></Link><span className={styles.meta}><Icon name="doc"/>{[featured.fileType,featured.meta,featured.category].filter(Boolean).join(" · ")}</span></div></motion.article><div className={styles.resourceRows}>{rows.map(r=><Link className={styles.resourceRow} key={r.id} href={resourceHref(r)}><ResourceMedia resource={r}/><div><span className={styles.eyebrow}>{resourceTypeLabels[r.type]}</span><h3>{r.title}</h3><span className={styles.rowMeta}>{r.meta}<i aria-hidden="true"/></span></div><Icon name="arrowRight"/></Link>)}</div></div> : <ResourceEmpty title="A clearer road starts with useful knowledge." text="Our guides and insights are being prepared. Contact the team for the guidance you need."/>}
      <details id="resource-library" className={styles.library}><summary>Browse the published library <span>{resources.filter(r=>r.type!=="faq").length} resources</span><Icon name="plus"/></summary><div>{resources.filter(r=>r.type!=="faq").map(r=><Link key={r.id} href={resourceHref(r)}><span>{resourceTypeLabels[r.type]}</span>{r.title}<Icon name="arrowRight"/></Link>)}</div></details>
    </section>
    <section id="videos" className={styles.videos} aria-labelledby="video-heading"><div className={styles.sectionHeader}><div><p className={styles.eyebrow}>Video learning</p><h2 id="video-heading">Watch. Learn. Apply.</h2><p>Practical videos to help you get the most from your RoadLenz solution.</p></div><SectionLink href="#video-episodes">Explore videos</SectionLink></div>{video ? <div className={styles.videoGrid}><motion.div {...reveal} className={styles.videoFeature}>{video.video && !videoFailed ? <video key={video.video} controls playsInline preload="metadata" poster={video.poster || undefined} aria-label={video.title} onLoadedMetadata={event=>{const duration=event.currentTarget.duration;if(Number.isFinite(duration)) setVideoDuration(`${Math.floor(duration/60)}:${String(Math.floor(duration%60)).padStart(2,"0")}`);}} onError={()=>setVideoFailed(true)}><source src={video.video}/></video> : <div className={styles.videoPlaceholder}><Icon name="play"/><h3>{video.title}</h3><p>{videoFailed ? "This video is temporarily unavailable." : "The video will be available here when it is uploaded."}</p><Link href={resourceHref(video)}>View resource details<Icon name="arrowRight"/></Link></div>}<div className={styles.videoCaption}><h3>{video.title}</h3><span>{videoDuration || video.meta}</span><Link href={resourceHref(video)} aria-label={`Details: ${video.title}`}><Icon name="arrowUpRight"/></Link></div></motion.div><div id="video-episodes" className={styles.episodes}>{videos.map((v,index)=><button type="button" key={v.id} onClick={()=>{setSelectedVideo(v.id);setVideoFailed(false);setVideoDuration("");}} aria-pressed={video.id===v.id}><span>{String(index+1).padStart(2,"0")}</span><ResourceMedia resource={v}/><span><strong>{v.title}</strong><small>{v.meta}</small></span><Icon name="play"/></button>)}{videos.length<3 && <p className={styles.episodeNote}>More learning, as it becomes available.<br/>New tutorials will appear here when published.</p>}</div></div> : <ResourceEmpty dark title="Your next lesson is on its way." text="Tutorials and webinars will appear here when published. Our team can help with your questions today."/>}</section>
    <section id="downloads" className={styles.downloads} aria-labelledby="download-heading"><div className={styles.sectionHeader}><div><p className={styles.eyebrow}>Downloadable tools</p><h2 id="download-heading">Tools for the road ahead.</h2></div><p>Published documents and practical resources<br/> for your next step.</p><div className={styles.rackControls}><button onClick={()=>moveRack(-1)} aria-label="Previous documents"><Icon name="chevronLeft"/></button><button onClick={()=>moveRack(1)} aria-label="Next documents"><Icon name="chevronRight"/></button></div></div>{downloads.length ? <div ref={rack} className={styles.documentRack} tabIndex={0} role="region" aria-label="Downloadable documents. Scroll horizontally.">{downloads.map(r=><article key={r.id}><Link href={resourceHref(r)} aria-label={`Read about ${r.title}`}><ResourceMedia resource={r} cover/></Link><h3>{r.title}</h3><div><span><Icon name="doc"/>{r.fileType}</span><a href={downloadHref(r.file)} download>Download<Icon name="arrowRight"/></a></div></article>)}</div> : <ResourceEmpty title="Practical tools are being prepared." text="Published files will appear here, ready to download."/>}</section>
    <div className={styles.supportGrid}><section id="documentation" aria-labelledby="documentation-heading"><p className={styles.eyebrow}>Documentation</p><h2 id="documentation-heading">Find the technical detail.</h2><p>Search published product documentation, user guides and technical resources.</p><form className={styles.search} onSubmit={event=>event.preventDefault()} role="search"><label className="sr-only" htmlFor="documentation-query">Search documentation</label><input id="documentation-query" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search documentation…"/><button type="submit" aria-label="Search documentation"><Icon name="search"/></button></form><div className={styles.categories} aria-label="Filter documentation by product category">{categories.map((c,index)=><button key={c.slug} aria-pressed={category===c.name} onClick={()=>setCategory(category===c.name ? "" : c.name)}><Icon name={["camera","video","camera","gps","shield","chip"][index%6]}/>{c.name}</button>)}</div><p className={styles.searchCount} role="status">{documents.length} published document{documents.length===1?"":"s"}{category ? ` in ${category}` : ""}</p><div className={styles.docResults}>{documents.map(r=><Link href={resourceHref(r)} key={r.id}><Icon name="doc"/><span>{r.title}</span><Icon name="arrowRight"/></Link>)}{!documents.length && <p>No published documents match this search. Try another term or category.</p>}</div></section><section id="help" aria-labelledby="help-heading"><p className={styles.eyebrow}>Help Centre</p><h2 id="help-heading">Answers when you need them.</h2><p>Find published answers, or contact our team for support.</p><div className={styles.faqs}>{faqs.map(faq=><details key={faq.id}><summary>{faq.title}<Icon name="plus"/></summary><p>{faq.answer}</p></details>)}{!faqs.length && <ResourceEmpty title="A question about your setup?" text="Our support team can help while the knowledge base grows."/>}</div><Link href="/contact" className={styles.button}>Visit Help Centre<Icon name="arrowRight"/></Link></section></div>
    <section id="case-studies" className={styles.cases} aria-labelledby="cases-heading"><div className={styles.sectionHeader}><div><p className={styles.eyebrow}>Case studies</p><h2 id="cases-heading">Stories from the road.</h2></div><p>Published, approved stories from fleet operations.</p></div>{cases.length ? cases.map(r=><Link href={resourceHref(r)} className={styles.caseStrip} key={r.id}><ResourceMedia resource={r}/><div><span className={styles.eyebrow}>Case study</span><h3>{r.title}</h3><p>{r.description}</p><span>Explore case study<Icon name="arrowRight"/></span></div></Link>) : <ResourceEmpty title="Real stories, when they are ready to share." text="Approved case studies will appear here after publication. Talk to the team about your fleet’s requirements."/>}</section>
    <section className={styles.cta}><div><p className={styles.eyebrow}>Get in touch</p><h2>Need help finding the right answer?</h2><p>Our team can help you get the most from your RoadLenz solution.</p></div><div><Link href="/contact" className={styles.whiteButton}>Talk to an Expert</Link><Link href="/request-quote" className={styles.button}>Request Quote<Icon name="arrowRight"/></Link></div></section>
  </div>;
}
