// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin-login" | "/admin/login" | "/book-demo" | "/contact" | "/customer-login" | "/dashboard" | "/global-presence" | "/industries" | "/industries/[slug]" | "/privacy" | "/products" | "/products/[slug]" | "/request-quote" | "/resources" | "/resources/[slug]" | "/search" | "/solutions" | "/solutions/[slug]" | "/technology" | "/technology/[slug]" | "/terms"
type AppRouteHandlerRoutes = "/admin/customers" | "/api/admin/customers" | "/api/admin/orders" | "/api/admin/orders/[id]" | "/api/admin/overview" | "/api/admin/settings" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/c/[entity]" | "/api/c/[entity]/[id]" | "/api/c/[entity]/reorder" | "/api/customer" | "/api/customer/notifications" | "/api/customer/orders" | "/api/customer/password" | "/api/customer/profile" | "/api/customer/save" | "/api/customer/ticket" | "/api/requests" | "/api/resources/files/[name]" | "/api/resources/upload" | "/api/supabase-test" | "/api/upload"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin-login": {}
  "/admin/customers": {}
  "/admin/login": {}
  "/api/admin/customers": {}
  "/api/admin/orders": {}
  "/api/admin/orders/[id]": { "id": string; }
  "/api/admin/overview": {}
  "/api/admin/settings": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/c/[entity]": { "entity": string; }
  "/api/c/[entity]/[id]": { "entity": string; "id": string; }
  "/api/c/[entity]/reorder": { "entity": string; }
  "/api/customer": {}
  "/api/customer/notifications": {}
  "/api/customer/orders": {}
  "/api/customer/password": {}
  "/api/customer/profile": {}
  "/api/customer/save": {}
  "/api/customer/ticket": {}
  "/api/requests": {}
  "/api/resources/files/[name]": { "name": string; }
  "/api/resources/upload": {}
  "/api/supabase-test": {}
  "/api/upload": {}
  "/book-demo": {}
  "/contact": {}
  "/customer-login": {}
  "/dashboard": {}
  "/global-presence": {}
  "/industries": {}
  "/industries/[slug]": { "slug": string; }
  "/privacy": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/request-quote": {}
  "/resources": {}
  "/resources/[slug]": { "slug": string; }
  "/search": {}
  "/solutions": {}
  "/solutions/[slug]": { "slug": string; }
  "/technology": {}
  "/technology/[slug]": { "slug": string; }
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
