"use client";
import {useState,useEffect,useCallback,type FormEvent} from "react";
import s from "./SecurityPanel.module.css";
type Account={id:string;name:string;email:string;username:string;role:string;active:boolean;primary:boolean;createdAt:string;lastLoginAt:string|null};
export default function AccountsPanel(){
 const [items,setItems]=useState<Account[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[sort,setSort]=useState("name");
 const [edit,setEdit]=useState<Account|"new"|null>(null),[reset,setReset]=useState<Account|null>(null),[confirm,setConfirm]=useState<{account:Account;action:"delete"|"disable"}|null>(null);
 const refresh=useCallback(async()=>{try{const res=await fetch("/api/admin/users",{cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error);setItems(data.items);}catch(e){setError(e instanceof Error?e.message:"Could not load accounts.");}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();const handler=()=>void refresh();window.addEventListener("roadlenz:admin-refresh",handler);return()=>window.removeEventListener("roadlenz:admin-refresh",handler);},[refresh]);
 async function save(method:string,id?:string,body?:Record<string,unknown>){setBusy(true);setError("");setMessage("");try{const res=await fetch(`/api/admin/users${id?`/${id}`:""}`,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await res.json();if(!res.ok)throw new Error(data.error || "Could not save account.");setEdit(null);setReset(null);setConfirm(null);setMessage(method==="POST"?"Admin user created.":method==="DELETE"?"Admin user deleted.":"Admin user updated. Existing sessions revoked.");window.dispatchEvent(new Event("roadlenz:admin-refresh"));}catch(e){setError(e instanceof Error?e.message:"Could not save account.");}finally{setBusy(false);}}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void save(edit==="new"?"POST":"PATCH",edit && edit!=="new"?edit.id:undefined,data);}
 const visible=items.filter(u=>`${u.name} ${u.email} ${u.username} ${u.role}`.toLowerCase().includes(search.toLowerCase()) && (status==="all" || u.active===(status==="active"))).sort((a,b)=>sort==="created"?b.createdAt.localeCompare(a.createdAt):a.name.localeCompare(b.name));
 return <div className={s.panel}>{error && <p role="alert" className={s.error}>{error}</p>}{message && <p role="status" className={s.notice}>{message}</p>}<section className={s.card}><div className={s.rowBetween}><div><h2>Administrator accounts</h2><p className={s.muted}>Super Admins manage access. The primary account is protected.</p></div><button className={s.primary} onClick={()=>setEdit("new")}>Add Admin</button></div><div className={s.fields}><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, email, username or role"/></label><div className={s.row}><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="disabled">Disabled</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name A–Z</option><option value="created">Newest first</option></select></label></div></div>{loading?<p role="status">Loading administrators…</p>:<div className={s.scroll}><table className={s.table}><thead><tr>{["Name / account","Role","Status","Last login","Created","Actions"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(u=><tr key={u.id}><td><strong>{u.name}</strong><br/>{u.email}<br/><span className={s.muted}>{u.username}</span></td><td><span className={s.badge}>{u.role.replace("_"," ")}</span>{u.primary && <p className={s.muted}>Primary</p>}</td><td>{u.active?"Active":"Disabled"}</td><td>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():"Never"}</td><td>{new Date(u.createdAt).toLocaleDateString()}</td><td>{u.primary?<span className={s.muted}>Protected account</span>:<div className={s.row}><button onClick={()=>setEdit(u)}>Edit</button><button onClick={()=>setReset(u)}>Reset password</button><button onClick={()=>u.active?setConfirm({account:u,action:"disable"}):void save("PATCH",u.id,{active:true})} disabled={busy}>{u.active?"Disable":"Enable"}</button><button className={s.danger} onClick={()=>setConfirm({account:u,action:"delete"})}>Delete</button></div>}</td></tr>)}{!visible.length && <tr><td colSpan={6}>No administrators match your filters.</td></tr>}</tbody></table></div>}</section>
 {edit && <div className={s.overlay}><section className={s.dialog} role="dialog" aria-modal="true" aria-labelledby="account-title"><h2 id="account-title">{edit==="new"?"Add administrator":"Edit administrator"}</h2><form onSubmit={submit}><div className={s.fields}><label>Name<input name="name" defaultValue={edit==="new"?"":edit.name} required maxLength={120} autoFocus/></label><label>Email<input name="email" type="email" defaultValue={edit==="new"?"":edit.email} required/></label><label>Username<input name="username" defaultValue={edit==="new"?"":edit.username} pattern="[a-zA-Z0-9._\-]{3,64}"/></label><label>Role<select name="role" defaultValue={edit==="new"?"ADMIN":edit.role}><option>ADMIN</option><option>SUPER_ADMIN</option></select></label>{edit==="new" && <label>Initial password<input name="password" type="password" required minLength={12} maxLength={128} autoComplete="new-password"/></label>}</div><p className={s.muted}>{edit==="new"?"Passwords require 12–128 characters, uppercase, lowercase, a number and a symbol.":"Saving changes revokes this account’s existing sessions."}</p><div className={s.row}><button className={s.primary} disabled={busy}>Save account</button><button type="button" onClick={()=>setEdit(null)} disabled={busy}>Cancel</button></div>{error && <p role="alert" className={s.error}>{error}</p>}</form></section></div>}
 {reset && <div className={s.overlay}><section className={s.dialog} role="dialog" aria-modal="true" aria-labelledby="reset-title"><h2 id="reset-title">Reset password for {reset.name}</h2><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);if(data.get("password")!==data.get("confirm")){setError("Passwords do not match.");return;}void save("PATCH",reset.id,{password:data.get("password")});}}><div className={s.fields}><label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required autoFocus/></label><label>Confirm password<input name="confirm" type="password" autoComplete="new-password" required/></label></div><p className={s.muted}>Use 12–128 characters with uppercase, lowercase, a number and a symbol. All sessions will be revoked.</p><div className={s.row}><button disabled={busy} className={s.primary}>Reset password</button><button type="button" onClick={()=>setReset(null)} disabled={busy}>Cancel</button></div>{error && <p role="alert" className={s.error}>{error}</p>}</form></section></div>}
 {confirm && <div className={s.overlay}><section className={s.dialog} role="alertdialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title">{confirm.action==="delete"?"Delete":"Disable"} {confirm.account.name}?</h2><p className={s.muted}>{confirm.action==="delete"?"This removes the administrator account permanently.":"This blocks sign-in until the account is enabled."} All existing sessions will be revoked.</p><div className={s.row}><button autoFocus onClick={()=>setConfirm(null)} disabled={busy}>Cancel</button><button className={s.danger} disabled={busy} onClick={()=>void save(confirm.action==="delete"?"DELETE":"PATCH",confirm.account.id,confirm.action==="disable"?{active:false}:undefined)}>Confirm {confirm.action}</button></div>{error && <p role="alert" className={s.error}>{error}</p>}</section></div>}</div>;
}
