"use client";
import Link from "next/link";
import { useEffect, useRef } from "react";
import { ArrowRight, ChevronRight, MapPin, Route, Video, ShieldCheck, Bell, ChartNoAxesCombined, FileText, UsersRound, Truck, Gauge, Clock3, Satellite, Radio, Cloud, Monitor, Settings2, Fence, Smartphone, Layers3, CircleCheck, Download, Search, Play, Building2, LockKeyhole, Camera, Database, Fuel } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { technologyPages, primaryTechnologyPages, type TechnologyPageData, type VisualKind } from "./technologyPages";
import styles from "./TechnologyRoutePage.module.css";
const icons: Record<string, LucideIcon> = { map: MapPin, route: Route, video: Video, shield: ShieldCheck, alerts: Bell, chart: ChartNoAxesCombined, report: FileText, users: UsersRound, truck: Truck, gauge: Gauge, clock: Clock3, satellite: Satellite, radio: Radio, cloud: Cloud, monitor: Monitor, settings: Settings2, fence: Fence, mobile: Smartphone, layers: Layers3, check: CircleCheck, download: Download, search: Search, play: Play, building: Building2, lock: LockKeyhole, camera: Camera, database: Database, fuel: Fuel };
function HeadingText({ text }: { text: string }) {
  const phrases: Record<string, string> = {
    "Fleet Intelligence Wherever You Go": "Wherever You Go",
    "Built to scale with your business.": "your business.",
    "Smarter alerts. Faster response.": "Faster response.",
  };
  const emphasis = phrases[text] ?? (text.startsWith("Explore ") ? text.slice(8) : text.slice(text.lastIndexOf(" ") + 1));
  return <>{text.slice(0, text.length - emphasis.length)}<em>{emphasis}</em></>;
}
function Glyph({ name }: { name: string }) { const Symbol = icons[name] ?? Layers3; return <Symbol aria-hidden="true" />; }
function Screen({ page }: { page: TechnologyPageData }) { return <div className={styles.productScreen}><div className={styles.screenBar}><span className={styles.brand}>RoadLenz</span><span>{page.label}</span><i className={styles.liveDot} /></div><img src={`/media/technology/desktop/${page.desktop}.png`} width={1440} height={900} alt={`RoadLenz ${page.label.toLowerCase()} desktop dashboard illustration`} fetchPriority="high" /></div>; }
function Phone({ name, alt }: { name: string; alt: string }) { return <div className={styles.phone}><img src={`/media/technology/software/${name}.png`} width={895} height={2000} alt={alt} /></div>; }
export function TechnologyHero({ page }: { page: TechnologyPageData }) {
  const mobile = page.slug === "mobile-access";
  return <section id="overview" className={styles.hero}><div className={styles.shell}>
    <div className={styles.pageNav}><nav aria-label="Breadcrumb"><Link href="/">Home</Link><ChevronRight /><Link href="/technology">Technology</Link><ChevronRight /><span aria-current="page">{page.label}</span></nav><nav aria-label="On this page">{[["Overview","overview"],["How It Works","how-it-works"],["Features","capabilities"],["Benefits","benefits"],["Output","output"]].map(([title,id])=><a key={id} href={`#${id}`}>{title}</a>)}</nav></div>
    {mobile && <h1 className={styles.mobileTitle}><HeadingText text={page.title}/></h1>}
    <div className={styles.heroGrid}><div className={styles.heroCopy}><span className={styles.eyebrow}>{page.eyebrow}</span>{!mobile && <h1><HeadingText text={page.title}/></h1>}<p className={styles.subtitle}>{page.subtitle}</p><p className={styles.description}>{page.description}</p><div className={styles.actions}><Link href="/book-demo" className={styles.primaryButton}>Request a Demo <ArrowRight /></Link><Link href={mobile ? "/contact" : "#capabilities"} className={styles.secondaryButton}>{mobile ? "Ask About Mobile Access" : "Explore Features"}<ArrowRight /></Link></div><ul className={styles.indicators}>{page.indicators.map(label=><li key={label}><CircleCheck />{label}</li>)}</ul></div>
    <div className={`${styles.heroVisual} ${mobile ? styles.mobileVisual : ""}`}>
      {page.scene && <img className={styles.scene} src={page.scene} alt="" aria-hidden="true" />}
      {mobile ? <div className={styles.phoneTrio}><Phone name="overview" alt="RoadLenz mobile fleet overview" /><Phone name="fleet-map" alt="RoadLenz mobile live map" /><Phone name="video-map" alt="RoadLenz mobile camera view" /></div> : <><Screen page={page} /><div className={styles.heroPhone}><Phone name={page.mobile} alt={`RoadLenz ${page.label.toLowerCase()} mobile app`} /></div></>}
      <div className={styles.visualStatus}><span className={styles.iconBox}><Glyph name={page.icon} /></span><div><strong>{page.label}</strong><small><i className={styles.liveDot} />Connected fleet workspace</small></div></div>
    </div></div></div></section>;
}
export function TechnologyIntro({ page }: { page: TechnologyPageData }) { return <section className={styles.intro} aria-label="About this module"><div className={`${styles.shell} ${styles.introGrid}`}><article><span className={styles.iconBox}><Glyph name={page.icon} /></span><div><h2>What is {page.label === "Tracking" ? "GPS Tracking" : page.label}?</h2><p>{page.definition}</p></div></article><article><span className={styles.iconBox}><Layers3 /></span><div><h2>What is it used for?</h2><p>{page.uses}</p></div></article></div></section>; }
function SectionHeading({ label, title, copy }: { label: string; title: string; copy?: string }) { return <header className={styles.sectionHeading}><span className={styles.eyebrow}>{label}</span><h2><HeadingText text={title}/></h2>{copy && <p>{copy}</p>}</header>; }
export function TechnologyProcess({ page }: { page: TechnologyPageData }) { return <section id="how-it-works" className={`${styles.section} ${styles.tinted}`}><div className={styles.shell}><SectionHeading label="How it works" title={page.processTitle} /><ol className={styles.process}>{page.steps.map((step,index)=><li key={step.title} data-reveal><span className={styles.processIcon}><Glyph name={step.icon} /></span><span className={styles.stepNumber}>{String(index+1).padStart(2,"0")}</span><h3>{step.title}</h3><p>{step.copy}</p>{index<3 && <ArrowRight className={styles.connector} />}</li>)}</ol></div></section>; }
export function TechnologyFeatureGrid({ page }: { page: TechnologyPageData }) { return <section id="capabilities" className={styles.section}><div className={styles.shell}><SectionHeading label="Key features" title="Everything you need in one connected workflow." /><div className={styles.features}>{page.features.map((feature,index)=><article key={feature.title} className={styles.featureCard} data-reveal><span className={styles.iconBox}><Glyph name={feature.icon} /></span><span className={styles.featureNumber}>{String(index+1).padStart(2,"0")}</span><h3>{feature.title}</h3><p>{feature.copy}</p><div className={styles.featureFooter}><span />{page.label} intelligence<ArrowRight /></div></article>)}</div></div></section>; }
export function TechnologyBenefits({ page }: { page: TechnologyPageData }) { return <section id="benefits" className={`${styles.section} ${styles.tinted}`}><div className={styles.shell}><SectionHeading label="Benefits" title={page.benefitsTitle} /><div className={styles.benefitGrid}><div className={styles.benefits}>{page.benefits.map(benefit=><article key={benefit.title} data-reveal><span className={styles.iconBox}><Glyph name={benefit.icon} /></span><div><h3>{benefit.title}</h3><p>{benefit.copy}</p></div></article>)}</div><div className={`${styles.benefitVisual} ${!page.scene ? styles.dashboardBenefit : ""}`}>{page.scene ? <img src={page.scene} alt={`${page.label} in a fleet operating environment`} loading="lazy" /> : <img src={`/media/technology/desktop/${page.desktop}.png`} alt={`Illustrative ${page.label.toLowerCase()} workspace`} loading="lazy" />}<div><span className={styles.eyebrow}>Connected operations</span><p>{page.subtitle}</p></div></div></div></div></section>; }
export function InsightPreview({ kind, page, title }: { kind: VisualKind; page: TechnologyPageData; title: string }) {
  if(kind==="map"||kind==="route") return <div className={`${styles.preview} ${styles.mapPreview}`}><img src={`/media/technology/desktop/${kind==="map"?"tracking":"history"}.png`} alt="" loading="lazy" /><svg viewBox="0 0 240 130" aria-hidden="true"><path className={styles.routePath} d="M24 105 C55 90 50 42 86 55 S155 112 168 60 S199 51 220 24" /><circle cx="24" cy="105" r="5"/><circle cx="220" cy="24" r="5"/></svg><small>{kind==="route"?"Route playback":"Fleet locations"}</small></div>;
  if(kind==="chart") return <div className={styles.preview}><div className={styles.chartLabel}>ACTIVITY TREND <span>7 days</span></div><div className={styles.bars}>{[35,58,42,76,63,88,72,94,68,85,74,95].map((n,i)=><i key={i} style={{height:`${n}%`}} />)}</div><small>Illustrative activity</small></div>;
  if(kind==="status") return <div className={`${styles.preview} ${styles.kpis}`}>{(title.includes("Trip") || title.includes("Journey") ? [["Distance","342 km"],["Duration","5h 12m"],["Avg. speed","68 km/h"],["Stops","8"]] : [["Fleet","36"],["Moving","2"],["Stopped","3"],["Offline","31"]]).map(([a,b])=><div key={a}><small>{a}</small><strong>{b}</strong></div>)}</div>;
  if(kind==="table") return <div className={styles.preview}><div className={styles.miniTable}><b>Report</b><b>Format</b>{(title.includes("Safety") ? ["Road event","Driver event","Device alert"] : title.includes("Idle") || title.includes("Stops") ? ["Ignition idle","Stopped period","Stop duration"] : title.includes("Company") ? ["Company activity","Fleet distance","Vehicle trips"] : ["Trip summary","GPS distance","Idle activity"]).map(n=><span key={n}>{n}<em>CSV / PDF</em></span>)}</div><small><Download size={12}/> Export preview</small></div>;
  if(kind === "video") {
    if (/evidence/i.test(title)) return <div className={`${styles.preview} ${styles.evidencePreview}`} data-video-preview="evidence"><div className={styles.evidenceThumb}><img src="/media/solutions/logistics-hero.jpg" alt="Illustrative vehicle scene attached to an evidence record" loading="lazy"/><span><ShieldCheck/> Event record</span></div><div className={styles.evidenceFile}><FileText/><div><strong>Journey evidence.mp4</strong><small>Front camera · 00:32</small></div><Download/></div><div className={styles.evidenceReady}><CircleCheck/> Ready for review</div></div>;
    if (/event|clip/i.test(title)) return <div className={`${styles.preview} ${styles.eventPreview}`} data-video-preview="event"><img src="/media/solutions/taxi-hero.jpg" alt="Illustrative night-time road scene for an event clip" loading="lazy"/><span className={styles.eventBadge}><ShieldCheck/> Event detected</span><div className={styles.eventTarget}/><div className={styles.clipFooter}><span>EVENT CLIP</span><span>00:12 / 00:30</span></div></div>;
    if (/playback|record/i.test(title)) return <div className={`${styles.preview} ${styles.playbackPreview}`} data-video-preview="playback"><img src="/images/home-cta/fleet-road.webp" alt="Illustrative recorded highway journey" loading="lazy"/><span className={styles.recordingBadge}>FRONT CAMERA · RECORDED</span><div className={styles.playbackControls}><div><Play/><span>09:42:18</span><span>1×</span></div><div className={styles.playbackTrack}><i/><b/></div><div><small>09:40</small><small>09:45</small><small>09:50</small></div></div></div>;
    return <div className={`${styles.preview} ${styles.videoPreview}`} data-video-preview="live"><img src="/media/technology/desktop/video.png" alt="RoadLenz live multi-camera grid" loading="lazy" /><span><Video /></span><small><i className={styles.liveDot}/> Live camera channels</small></div>;
  }
  if(kind==="alerts") return <div className={styles.preview}>{(title.includes("ADAS") ? ["Collision warning","Lane departure","Close distance"] : title.includes("Historical") ? ["Trip started","Vehicle stopped","Trip completed"] : ["Safety event","Geofence event","Vehicle status"]).map((n,i)=><div className={styles.alertRow} key={n}><Bell/><span>{n}<small>{i+1} min ago</small></span><i /></div>)}</div>;
  if(kind==="groups") return <div className={`${styles.preview} ${styles.groupPreview}`}><span><Building2 />Company workspace</span><i /><div><span>Fleet A</span><span>Fleet B</span></div><small><LockKeyhole size={12}/> Role-based access</small></div>;
  return <div className={`${styles.preview} ${styles.mobilePreview}`}><Phone name={page.mobile} alt="" /><div><Smartphone/><strong>{page.label}</strong><small>Fleet access on the go</small></div></div>;
}
export function TechnologyOutputs({ page }: { page: TechnologyPageData }) { return <section id="output" className={styles.section}><div className={styles.shell}><SectionHeading label="Output & insights" title={page.outputTitle} copy="Illustrative previews of the information available in your fleet workflow." /><div className={styles.outputs}>{page.outputs.map(out=><article key={out.title} data-reveal><InsightPreview kind={out.kind} page={page} title={out.title}/><h3>{out.title}</h3><p>{out.copy}</p></article>)}</div></div></section>; }
export function RelatedTechnologyModules({ page }: { page: TechnologyPageData }) { const related=page.related.map(slug=>technologyPages.find(p=>p.slug===slug)).filter((p):p is TechnologyPageData=>Boolean(p));return <section className={`${styles.section} ${styles.relatedSection}`}><div className={styles.shell}><SectionHeading label="Related modules" title="Keep your fleet intelligence connected."/><nav className={styles.related} aria-label="Related technology modules">{related.map(item=><Link key={item.slug} href={`/technology/${item.slug}`}><span className={styles.iconBox}><Glyph name={item.icon}/></span><div><h3>{item.label}</h3><p>{item.subtitle}</p></div><ArrowRight/></Link>)}</nav></div></section>; }
export function TechnologyCTA({ page }: { page: TechnologyPageData }) {return <section className={styles.ctaSection}><div className={styles.shell}><div className={styles.cta}><div><span className={styles.eyebrow}>RoadLenz technology</span><h2><HeadingText text={page.ctaTitle}/></h2><p>{page.ctaCopy}</p></div><div className={styles.actions}><Link className={styles.primaryButton} href="/book-demo">Request a Demo<ArrowRight/></Link><Link className={styles.ctaContact} href="/contact">Contact our team<ArrowRight/></Link></div></div></div></section>; }
export default function TechnologyRoutePage({ route: page }: { route: TechnologyPageData }) {
  const root=useRef<HTMLElement>(null);
  useEffect(()=>{const media=window.matchMedia("(prefers-reduced-motion: reduce)");const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){if(!media.matches)entry.target.animate([{opacity:.65,transform:"translateY(10px)"},{opacity:1,transform:"translateY(0)"}],{duration:450,easing:"ease-out"});observer.unobserve(entry.target);}}},{threshold:.12});root.current?.querySelectorAll("[data-reveal]").forEach(el=>observer.observe(el));return()=>observer.disconnect();},[page.slug]);
  return <main ref={root} className={styles.page}><TechnologyHero page={page}/><nav className={styles.moduleNav} aria-label="Technology modules"><div className={styles.shell}>{primaryTechnologyPages.map(module=><Link key={module.slug} href={`/technology/${module.slug}`} aria-current={module.slug===page.slug?"page":undefined}><Glyph name={module.icon}/>{module.label}</Link>)}</div></nav><TechnologyIntro page={page}/><TechnologyProcess page={page}/><TechnologyFeatureGrid page={page}/><TechnologyBenefits page={page}/><TechnologyOutputs page={page}/><RelatedTechnologyModules page={page}/><TechnologyCTA page={page}/></main>;
}
